version: '3.5'

networks:
  dev:
    driver: bridge

services:
  my-project: 
    image: docker.io/library/myproject
    depends_on:
      - app_db
    container_name: myproject-services
    ports:
      - "8088:80"
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=app_db;Port=5432;Database=SampleDbDriver;Username=postgres;Password=postgres;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
    networks: 
      - dev

  app_db: 
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=SampleDbDriver
    ports: 
      - "5433:5432"
    restart: always
    volumes: 
      - app_data:/var/lib/postgresql/data
    networks: 
      - dev

volumes: 
  app_data:
